name: Build LaTeX document
on:
  push:
    branches:
      - master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ./
          root_file: ./4_Wissenschaftliche_Arbeit_Typ_Matrikelnummer_Kurs_Name.tex
          
      - name: Export
        uses: actions/upload-artifact@v2
        with:
          name: Studienarbeit
          path: ./4_Wissenschaftliche_Arbeit_Typ_Matrikelnummer_Kurs_Name.pdf
          
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./4_Wissenschaftliche_Arbeit_Typ_Matrikelnummer_Kurs_Name.pdf
          tag: "Release"
          overwrite: true
          body: "Template für wissenschaftliche Arbeiten"
